"use client";
import { useState, useMemo } from "react";
import Nav from "@/components/ui/Nav";
import Footer from "@/components/ui/Footer";
import UploadZone from "@/components/ui/UploadZone";
import InsightPanel from "@/components/ui/InsightPanel";
import AiAssistant from "@/components/ui/AiAssistant";
import Card from "@/components/ui/Card";
import Button from "@/components/ui/Button";
import KpiCard from "@/components/ui/charts/KpiCard";
import LineAreaChart from "@/components/ui/charts/LineAreaChart";
import BarChart from "@/components/ui/charts/BarChart";
import DoughnutChart from "@/components/ui/charts/DoughnutChart";
import RadarChart from "@/components/ui/charts/RadarChart";
import PolarChart from "@/components/ui/charts/PolarChart";
import ScatterChart from "@/components/ui/charts/ScatterChart";
import BubbleChart from "@/components/ui/charts/BubbleChart";
import MixedChart from "@/components/ui/charts/MixedChart";
import Heatmap from "@/components/ui/charts/Heatmap";
import ChartSwitcher from "@/components/ui/charts/ChartSwitcher";
import {
  Download, Share2, RefreshCw, Filter, Calendar, Sparkles,
  FileText, Copy, Check, Brain,
} from "lucide-react";

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu"];

export default function Dashboard() {
  const [hasData, setHasData] = useState(false);
  const [shareCopied, setShareCopied] = useState(false);
  const [range, setRange] = useState<"1M" | "3M" | "6M" | "1Y">("6M");

  const monthsRange = useMemo(() => {
    if (range === "1M") return MONTHS.slice(-1);
    if (range === "3M") return MONTHS.slice(-3);
    if (range === "6M") return MONTHS.slice(0, 6);
    return MONTHS;
  }, [range]);

  const sales = [45200, 52100, 38900, 61500, 57800, 68400, 72100, 79300].slice(0, monthsRange.length);
  const target = [40000, 45000, 50000, 50000, 55000, 60000, 65000, 70000].slice(0, monthsRange.length);
  const profit = [12300, 15800, 9200, 19400, 17900, 22300, 24500, 27800].slice(0, monthsRange.length);

  const downloadAlert = (what: string) => alert(`✅ ${what} berhasil disiapkan!\n(Demo prototype — file aktual akan tersedia di versi production.)`);

  const onShare = async () => {
    const url = typeof window !== "undefined" ? window.location.href : "";
    try {
      if (navigator.share) {
        await navigator.share({ title: "Grafio Dashboard", url });
      } else {
        await navigator.clipboard.writeText(url);
        setShareCopied(true);
        setTimeout(() => setShareCopied(false), 1800);
      }
    } catch {
      /* user cancelled */
    }
  };

  return (
    <main className="min-h-screen bg-bgDeep relative">
      <Nav />
      <div className="absolute inset-0 grid-bg pointer-events-none opacity-50" />
      <div className="relative max-w-7xl mx-auto px-6 py-10">
        {/* Header */}
        <div className="flex flex-wrap items-end justify-between gap-4 mb-8">
          <div>
            <p className="text-xs uppercase tracking-[0.25em] text-cyan mb-2">Dashboard</p>
            <h1 className="text-3xl md:text-4xl font-syne font-bold text-white">
              Workspace Analitik
            </h1>
            <p className="text-muted text-sm mt-1">
              {hasData ? "Laporan sales pipeline · 8 bulan · auto-generated by AI" : "Mulai dengan upload data atau coba demo"}
            </p>
          </div>
          {hasData && (
            <div className="flex items-center gap-2 flex-wrap">
              <div className="flex items-center gap-1 bg-bgSurface border border-borderColor rounded-md p-1">
                {(["1M", "3M", "6M", "1Y"] as const).map((r) => (
                  <button
                    key={r}
                    onClick={() => setRange(r)}
                    className={`px-3 py-1 text-xs rounded transition-all ${
                      range === r ? "bg-cyan text-bgDeep font-semibold" : "text-muted hover:text-white"
                    }`}
                  >
                    {r}
                  </button>
                ))}
              </div>
              <Button variant="ghost" size="sm" onClick={() => setHasData(false)}>
                <RefreshCw className="w-3.5 h-3.5" /> Reset
              </Button>
              <Button variant="ghost" size="sm" onClick={() => alert("Filter panel akan tersedia segera")}>
                <Filter className="w-3.5 h-3.5" /> Filter
              </Button>
            </div>
          )}
        </div>

        {!hasData ? (
          <div className="max-w-3xl mx-auto">
            <UploadZone onDemo={() => setHasData(true)} />
          </div>
        ) : (
          <div className="space-y-6">
            {/* KPI ROW */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <KpiCard label="Total Revenue" value="Rp 475M" change={12.4} spark={[20, 30, 28, 41, 38, 52, 60, 68]} color="#00D4FF" />
              <KpiCard label="Customers" value="12.8K" change={8.1} spark={[10, 12, 18, 22, 28, 34, 41, 48]} color="#00FFB3" />
              <KpiCard label="ROAS" value="3.4×" change={-2.3} spark={[40, 38, 41, 35, 32, 30, 28, 30]} color="#FF6FB5" />
              <KpiCard label="Avg Order" value="Rp 285K" change={4.7} spark={[28, 30, 31, 33, 32, 34, 35, 37]} color="#7B5EA7" />
            </div>

            {/* MAIN CHART + INSIGHT */}
            <div className="grid lg:grid-cols-3 gap-6">
              <div className="lg:col-span-2">
                <Card>
                  <div className="flex items-center justify-between mb-2">
                    <div>
                      <p className="text-xs uppercase tracking-widest text-cyan">Recommended by AI</p>
                      <h3 className="font-syne font-bold text-white text-lg">Sales vs Target vs Profit</h3>
                    </div>
                    <Calendar className="w-4 h-4 text-muted" />
                  </div>
                  <ChartSwitcher
                    labels={monthsRange}
                    series={[
                      { label: "Sales", data: sales },
                      { label: "Target", data: target },
                      { label: "Profit", data: profit },
                    ]}
                  />
                </Card>
              </div>
              <div>
                <AiAssistant />
              </div>
            </div>

            {/* INSIGHTS */}
            <InsightPanel />

            {/* CHART GRID */}
            <div className="grid lg:grid-cols-3 md:grid-cols-2 gap-5">
              <Card>
                <div className="flex items-center justify-between mb-3">
                  <div>
                    <p className="text-[10px] uppercase tracking-widest text-cyan">Mixed</p>
                    <h4 className="font-syne font-semibold text-white text-sm">Forecast vs Actual</h4>
                  </div>
                  <Sparkles className="w-3.5 h-3.5 text-cyan" />
                </div>
                <MixedChart
                  height={220}
                  labels={monthsRange}
                  bars={[{ label: "Aktual", data: sales, color: "#00D4FF" }]}
                  lines={[{ label: "Forecast", data: target, color: "#7B5EA7" }]}
                />
              </Card>
              <Card>
                <p className="text-[10px] uppercase tracking-widest text-cyan">Distribution</p>
                <h4 className="font-syne font-semibold text-white text-sm mb-3">Channel Mix</h4>
                <DoughnutChart
                  height={220}
                  labels={["Direct", "SEO", "Ads", "Social"]}
                  data={[42, 25, 22, 11]}
                  centerLabel="100%"
                />
              </Card>
              <Card>
                <p className="text-[10px] uppercase tracking-widest text-cyan">Multi-metric</p>
                <h4 className="font-syne font-semibold text-white text-sm mb-3">Performance Radar</h4>
                <RadarChart
                  height={240}
                  labels={["Speed", "Quality", "Price", "Support", "Reach", "UX"]}
                  series={[
                    { label: "Brand A", data: [9, 8, 7, 9, 8, 9] },
                    { label: "Brand B", data: [6, 7, 9, 6, 7, 6] },
                  ]}
                />
              </Card>
              <Card>
                <p className="text-[10px] uppercase tracking-widest text-cyan">Polar</p>
                <h4 className="font-syne font-semibold text-white text-sm mb-3">Region Share</h4>
                <PolarChart
                  height={240}
                  labels={["Jakarta", "Bandung", "Surabaya", "Medan", "Bali"]}
                  data={[42, 18, 22, 10, 8]}
                />
              </Card>
              <Card>
                <p className="text-[10px] uppercase tracking-widest text-cyan">Correlation</p>
                <h4 className="font-syne font-semibold text-white text-sm mb-3">Price × Conversion</h4>
                <ScatterChart
                  height={240}
                  series={[
                    {
                      label: "Produk A",
                      data: [
                        { x: 50, y: 4.2 }, { x: 80, y: 3.8 }, { x: 100, y: 3.4 },
                        { x: 120, y: 2.8 }, { x: 150, y: 2.4 }, { x: 180, y: 2.0 },
                        { x: 200, y: 1.8 },
                      ],
                    },
                    {
                      label: "Produk B",
                      data: [
                        { x: 60, y: 3.6 }, { x: 90, y: 3.2 }, { x: 110, y: 2.9 },
                        { x: 140, y: 2.5 }, { x: 170, y: 2.1 }, { x: 220, y: 1.6 },
                      ],
                    },
                  ]}
                />
              </Card>
              <Card>
                <p className="text-[10px] uppercase tracking-widest text-cyan">Segments</p>
                <h4 className="font-syne font-semibold text-white text-sm mb-3">Customer Cluster</h4>
                <BubbleChart
                  height={240}
                  series={[
                    {
                      label: "High value",
                      data: [
                        { x: 30, y: 80, r: 18 }, { x: 45, y: 75, r: 22 },
                        { x: 60, y: 90, r: 16 },
                      ],
                    },
                    {
                      label: "Mid",
                      data: [
                        { x: 25, y: 50, r: 12 }, { x: 40, y: 55, r: 14 },
                        { x: 55, y: 60, r: 10 }, { x: 70, y: 50, r: 16 },
                      ],
                    },
                    {
                      label: "Low",
                      data: [
                        { x: 15, y: 25, r: 8 }, { x: 30, y: 20, r: 10 },
                        { x: 45, y: 30, r: 9 }, { x: 60, y: 22, r: 7 },
                      ],
                    },
                  ]}
                />
              </Card>
              <Card className="md:col-span-2">
                <p className="text-[10px] uppercase tracking-widest text-cyan">Stacked Bar</p>
                <h4 className="font-syne font-semibold text-white text-sm mb-3">Revenue by Segment</h4>
                <BarChart
                  height={240}
                  stacked
                  labels={monthsRange}
                  series={[
                    { label: "Enterprise", data: sales.map((s) => Math.round(s * 0.5)), color: "#00D4FF" },
                    { label: "SMB", data: sales.map((s) => Math.round(s * 0.3)), color: "#7B5EA7" },
                    { label: "Startup", data: sales.map((s) => Math.round(s * 0.2)), color: "#00FFB3" },
                  ]}
                />
              </Card>
              <Card>
                <p className="text-[10px] uppercase tracking-widest text-cyan">Heatmap</p>
                <h4 className="font-syne font-semibold text-white text-sm mb-3">Activity by Day × Hour</h4>
                <Heatmap
                  height={240}
                  rows={["Sen", "Sel", "Rab", "Kam", "Jum", "Sab", "Min"]}
                  cols={["08", "10", "12", "14", "16", "18", "20"]}
                  values={[
                    [12, 18, 24, 31, 28, 22, 14],
                    [16, 24, 30, 38, 34, 26, 18],
                    [18, 28, 35, 42, 38, 30, 20],
                    [20, 30, 38, 45, 40, 32, 22],
                    [25, 36, 44, 52, 48, 38, 28],
                    [10, 14, 18, 22, 26, 30, 24],
                    [8, 10, 14, 18, 22, 26, 20],
                  ]}
                />
              </Card>
            </div>

            {/* DATA PREVIEW */}
            <Card>
              <div className="flex items-center justify-between mb-4">
                <div>
                  <p className="text-[10px] uppercase tracking-widest text-cyan">Raw Data</p>
                  <h4 className="font-syne font-semibold text-white text-sm">Preview (5 baris pertama)</h4>
                </div>
                <button
                  onClick={() => alert("Membuka full data table…")}
                  className="text-xs text-cyan hover:underline flex items-center gap-1"
                >
                  Lihat semua <FileText className="w-3 h-3" />
                </button>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-xs uppercase tracking-wider text-muted border-b border-borderColor">
                      <th className="py-3 pr-4">Bulan</th>
                      <th className="py-3 pr-4 text-right">Penjualan</th>
                      <th className="py-3 pr-4 text-right">Target</th>
                      <th className="py-3 pr-4 text-right">Profit</th>
                      <th className="py-3 pr-4 text-right">% Target</th>
                    </tr>
                  </thead>
                  <tbody className="text-white">
                    {monthsRange.map((m, i) => {
                      const pct = (sales[i] / target[i]) * 100;
                      const positive = pct >= 100;
                      return (
                        <tr key={m} className="border-b border-borderColor/50 hover:bg-bgElevated/50 transition-colors">
                          <td className="py-3 pr-4">{m}</td>
                          <td className="py-3 pr-4 text-right font-mono">{sales[i].toLocaleString("id")}</td>
                          <td className="py-3 pr-4 text-right font-mono text-muted">{target[i].toLocaleString("id")}</td>
                          <td className="py-3 pr-4 text-right font-mono">{profit[i].toLocaleString("id")}</td>
                          <td className={`py-3 pr-4 text-right font-mono ${positive ? "text-mint" : "text-danger"}`}>
                            {pct.toFixed(1)}%
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </Card>

            {/* ACTION BAR */}
            <div className="flex items-center gap-3 flex-wrap">
              <Button onClick={() => downloadAlert("PDF Report")}>
                <Download className="w-4 h-4" /> PDF Report
              </Button>
              <Button variant="ghost" onClick={() => downloadAlert("PNG Charts")}>
                <Download className="w-4 h-4" /> Download PNG
              </Button>
              <Button variant="ghost" onClick={() => downloadAlert("PowerPoint Slides")}>
                <Download className="w-4 h-4" /> Export PPT
              </Button>
              <Button variant="ghost" onClick={() => downloadAlert("CSV Cleaned")}>
                <Download className="w-4 h-4" /> Cleaned CSV
              </Button>
              <button
                onClick={onShare}
                className="ml-auto px-4 py-2.5 rounded-md border border-borderColor text-white hover:border-cyan hover:text-cyan transition-colors text-sm flex items-center gap-2"
              >
                {shareCopied ? <Check className="w-4 h-4 text-mint" /> : <Share2 className="w-4 h-4" />}
                {shareCopied ? "Link disalin" : "Share"}
              </button>
              <button
                onClick={() => navigator.clipboard?.writeText(window.location.href)}
                className="px-4 py-2.5 rounded-md border border-borderColor text-white hover:border-cyan hover:text-cyan transition-colors text-sm flex items-center gap-2"
                aria-label="Copy link"
              >
                <Copy className="w-4 h-4" /> Salin Link
              </button>
            </div>
          </div>
        )}
      </div>
      <Footer />
    </main>
  );
}
